### PR TITLE
fix: support --set boolean and numberic params

### PR DESCRIPTION
**Pull request by jbedard**
Didn't think of this one at first. Note that we'll have the same issue with numbers if there are any numeric options.

### CODE REVIEW

**Comment by songkeys** [comment]
> Note that we'll have the same issue with numbers if there are any numeric options.

Are there any numeric options available currently? Can we implement the logic as a precautionary measure?

**Comment by jbedard** [comment]
Yeah, I could do that if you'd like?

Note that just like boolean it will be an assumption that anything that "looks like" a number will be parsed as a number, just like "true" and "false" strings "look like" booleans are parsed as booleans. I think it's a safe assumption for now, especially since I don't think there are any variable string options?

**Comment by songkeys** [comment]
Yes, I agree. Please do it. Also, I noticed that this parameter is missing in the readme document. Could you also include it there?

**Comment by jbedard** [comment]
Updated 👍

**Comment by songkeys** [comment]
Thank you for the effort!

**Comment by jbedard** [comment]
Thanks for the quick review! 👍

**Pull request merged**
